### ISSUE TITLE
Add support for nested arrows

### ISSUE THREAD

**Issue by josephschorr** [authzed/spicedb#1022] opened 2022-11-28 21:45 UTC
Now that V0 API is fully removed, we should investigate adding support for nested arrows

Example:

```zed
definition namespace {
  relation view: user
}

definition namespace {
  relation parent: organization
}

definition document {
  relation parent: namespace
  permission view = parent->parent->view
}
```

**Comment by jzelinskie** [comment] 2022-11-28 21:55
This is a duplicate of: https://github.com/authzed/spicedb/issues/15

**Closed** 2022-11-28 21:55 UTC
Labels: priority/3 low, area/schema, state/needs discussion

**Comment by artie-shevchenko** [comment] 2023-06-16 21:52
can we change the priority of this ticket to get rid of the synthetic permission in user-defined roles: [Modeling Google Cloud IAM in SpiceDB](https://authzed.com/blog/google-cloud-iam-modeling#user-content-using-roles-to-make-decisions)?
