### ISSUE TITLE
datastore migrate not reading connection uri from ENV variable

### ISSUE THREAD

**Issue by thewunder** [authzed/spicedb#1114] opened 2023-01-23 17:39 UTC
I was working on a wrapper that reads credentials from AWS secrets manager and sets them as environment variables, and using them in spicedb serve was working, but not when running spicedb.

SPICEDB_DATASTORE_CONN_URI is set to "user:pass@tcp(dbhost)/database?parseTime=true"

which connects fine running 

`spicedb serve --datastore-engine=mysql --datastore-mysql-table-prefix=spicedb --http-enabled`

But gives me "unable to migrate to `head` revision: unable to compute target revision: unable to load driver migration revision: Error 1045: Access denied for user ''@'localhost' (using password: NO)"

When running

`spicedb datastore migrate head --datastore-engine=mysql --datastore-mysql-table-prefix=spicedb`

Passing the same conn-uri as cli option works.

Spicedb 1.16.1 was installed via the apt package on Ubuntu 22.04.1

**Comment by vroldanbet** [comment] 2023-01-23 17:58
@thewunder 👋🏻 I wasn't able to reproduce the problem. When I provided `SPICEDB_DATASTORE_CONN_URI` to `spicedb migrate` the user/pass was parsed as expected. Please note your command above shows `spicedb datastore migrate` but should be instead `spicedb migrate`.

Is it possible you are using special characters that are not being parsed/escaped correctly?

**Comment by thewunder** [comment] 2023-01-23 18:53
Removing the datastore parameter made no difference.

Here is a whole terminal session showing me setting the env var with password redacted, nothing exotic in terms of special characters I see. Again the exact same connection string wor

```
thewunder@computer:~/PhpstormProjects/arc$ SPICEDB_DATASTORE_CONN_URI="thewunder:password@tcp(localhost)/arc_local1?parseTime=true"
thewunder@computer:~/PhpstormProjects/arc$ echo $SPICEDB_DATASTORE_CONN_URI 
thewunder:password@tcp(localhost)/arc_local1?parseTime=true
thewunder@computer:~/PhpstormProjects/arc$ spicedb datastore migrate head --datastore-engine=mysql --datastore-mysql-table-prefix=spicedb_
12:42PM INF configured logging async=false format=auto log_level=info provider=zerolog
12:42PM INF configured opentelemetry tracing endpoint= insecure=false provider=none sampleRatio=0.2 service=spicedb v=0
12:42PM INF this is the latest released version of SpiceDB latest-released-version=v1.16.1
12:42PM INF migrating mysql datastore
12:42PM INF running migrations targetRevision=head
12:42PM ERR terminated with errors error="unable to migrate to `head` revision: unable to compute target revision: unable to load driver migration revision: Error 1045: Access denied for user ''@'localhost' (using password: NO)"
```

And with the connection string passed as a cli flag:

```
thewunder@computer:~/PhpstormProjects/arc$ spicedb migrate head --datastore-engine=mysql --datastore-mysql-table-prefix=spicedb_ --datastore-conn-uri=$SPICEDB_DATASTORE_CONN_URI
12:51PM INF configured logging async=false format=auto log_level=info provider=zerolog
12:51PM INF configured opentelemetry tracing endpoint= insecure=false provider=none sampleRatio=0.2 service=spicedb v=0
12:51PM INF this is the latest released version of SpiceDB latest-released-version=v1.16.1
12:51PM INF migrating mysql datastore
12:51PM INF running migrations targetRevision=head
12:51PM INF server already at requested revision targetRevision=head

**Comment by thewunder** [comment] 2023-01-25 16:49
@vroldanbet can you reproduce using that more detailed set of steps :arrow_up: or do you see any mistake in what I'm doing?

**Comment by vroldanbet** [comment] 2023-01-26 11:26
@thewunder unfortunately I cannot reproduce it. I've tried passing both `localhost` and `localhost:3306` and it just works fine 😕

**Comment by thewunder** [comment] 2023-01-27 22:45
@vroldanbet you mean like run spicedb with the go debugger? I have a functional go development environment so yes. I also have basically zero go experience.

**Comment by josephschorr** [comment] 2023-02-21 19:43
@thewunder any updates on this issue?

**Comment by josephschorr** [comment] 2023-04-05 15:59
Closing; please reopen if you were able to reproduce

**Closed by josephschorr** 2023-04-05 15:59 UTC
