### ISSUE TITLE
Test Flake: TestMySQLDatastore/QuantizedRevisions

### ISSUE THREAD

**Issue by josephschorr** [authzed/spicedb#946] opened 2022-10-26 18:49 UTC
```
--- FAIL: TestMySQLDatastore (53.82s)
    --- FAIL: TestMySQLDatastore/QuantizedRevisions (0.28s)
        --- FAIL: TestMySQLDatastore/QuantizedRevisions/QuantizedLower (0.05s)
            datastore_test.go:527: 
                	Error Trace:	/home/runner/work/spicedb/spicedb/internal/datastore/mysql/datastore_test.go:527
                	Error:      	Not equal: 
                	            	expected: 0x3
                	            	actual  : 0x4
                	Test:       	TestMySQLDatastore/QuantizedRevisions/QuantizedLower
```

**Comment by vroldanbet** [comment] 2022-10-28 17:22
Duplicate of https://github.com/authzed/spicedb/issues/911

**Closed by vroldanbet** 2022-10-28 17:22 UTC
Labels: area/flake
