### ISSUE TITLE
It would be nice if by specifying some relation we could use it as indirect inverse relation in schema as well

### ISSUE THREAD

**Issue by mmx86** [authzed/spicedb#2012] opened 2024-08-02 10:56 UTC
### Problem Statement

Our usecase requirements:
- Two levels of organizational units: spaces, which contain projects.
- User must be able to get role on project without having to get any space role.
- User has to be able to read basic info about parent space (title, etc.).

Right now what we do is we define service role on space, which we hide from main business logic, and this role is added/removed when user roles on projects change. 
```
definition user {}

definition space {
    relation role__user: user
    relation service_role__projects_user: user
    permission view = role__user + service_role__projects_user
}

definition project {
    relation resource__space: space
    relation role__user: user
}
```
Or, instead, we could do the same with space-project relations, instead of roles with the same result.
Anyway it feels like a hardcode. 
It would be nice to be able to solve this by schema itself, by being able to reference the inverse relations on the fly.

```
definition space {
    relation role__user: user

    // Space user or user of any child project
    permission view = role__user + project(->resource__space)#role__user  // syntax example
}

definition project {
    relation resource__space: space
    relation role__user: user
}
```

**Comment by vroldanbet** [comment] 2024-08-02 11:10
Duplicate of https://github.com/authzed/spicedb/issues/356

**Closed by vroldanbet** 2024-08-02 11:10 UTC
Labels: kind/proposal
