### ISSUE TITLE
Test Flake: TestMySQLMigrations

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb#802] opened 2022-09-06 22:11 UTC
```go
--- FAIL: TestMySQLMigrations (60.72s)
    mysql.go:81: 
        	Error Trace:	/home/runner/work/spicedb/spicedb/internal/datastore/mysql/mysql.go:81
        	            				/home/runner/work/spicedb/spicedb/internal/datastore/mysql/datastore_test.go:629
        	            				/home/runner/work/spicedb/spicedb/internal/datastore/mysql/datastore_test.go:577
        	Error:      	Received unexpected error:
        	            	reached retry deadline
        	Test:       	TestMySQLMigrations
```
Seen here: https://github.com/authzed/spicedb/runs/8214010816?check_suite_focus=true

**Comment by josephschorr** [comment] 2023-04-07 15:53
Spurious timeout due to the container not being ready. Stress tests unable to reproduce locally, so closing unless we see again

**Closed by josephschorr** 2023-04-07 15:53 UTC
Labels: kind/bug, priority/2 medium, area/datastore, area/tooling, kind/flake
