### ISSUE TITLE
Insure watch PG connection remains reusable after release

### ISSUE THREAD

**Issue by robinbraemer** [authzed/spicedb#293] opened 2021-11-19 23:05 UTC
I just want to make sure we are aware of it:

The watch crdb code https://github.com/authzed/spicedb/blob/a75cd6484c313c71dfd98072dadf0a4fffaed4d0/internal/datastore/crdb/watch.go#L29 and the crdb docs https://www.cockroachlabs.com/docs/v21.2/changefeed-for#considerations

` It is therefore critical that you close the connection, otherwise the application will be blocked forever on Rows.Close().`

 - Since you use a pgx.Pool underneath, are you sure that the connection gets closed after the context to Watch is canceled and that the pg connect is not just released back into the pool leaving the connection in an unusable state for next normal SQL queries?

**Comment by jason-who-codes** [comment] 2022-10-27 15:57
In addition to the connection close issue (which seems like a pretty significant one), the crdb docs linked above specifically call out that you should use a "dedicated database connection with _specific settings around result buffering_" because crbd tends to buffer results server-side, but that's not the desired behavior for changefeeds

**Comment by vroldanbet** [comment] 2022-12-13 08:53
@jakedt since you've been looking into Watch API performance and reliability, this seems relevant.

**Comment by jason-who-codes** [comment] 2023-02-20 23:43
I attempted to produce the scenario of a pgx pool poisoned with bad connections due to cancelled watches, but was unsuccessful in doing so. I wrote a pathological `watch` client that every few seconds sends the API request, reads the first result, and uses manual flow control to only consume one watch response every few seconds. In Java this is accomplished by implementing a [ClientResponseObserver](https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/ClientResponseObserver.html) which calls `clientCallStreamObserver.disableAutoRequestWithInitial(1)` in `beforeStart()` and `clientCallStreamObserver.request(1)` after a 5 second delay in each `onNext()`. This quickly led to the watcher getting `RESOURCE_EXHAUSTED: watch disconnected: watch fell too far behind and was disconnected` responses from SpiceDB.

Canceled watches did not cause other traffic (e.g. concurrent `check` API calls) to fail (as I would have expected if the connection pool had been poisoned with "undead" changefeed conenctions), but did cause the CRDB metrics `sql_new_conns` and `sql_pgwire_cancel_total` to increase. This seems to indicate that pgx's [asyncClose](https://github.com/jackc/pgconn/blob/v1.13.0/pgconn.go#L648-L650) function is being triggered, which opens a separate "connection" to issue [a cancellation signal](https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.10) to the server, which CRDB [handles here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/pgwire/server.go#L819-L828). The pool then opens a new connection to replace the one that was closed in response to the cancelled context.

I wasn't able to find much documentation on exactly how pgx handles context cancellation, but I did eventually find [this discussion](https://github.com/jackc/pgx/issues/659#issuecomment-572138754) which says:
> That was what led to making context cancellation close the connection.

So, it seems that pgx's handling of context cancellation has the desired effect of preventing a "bad" connection from being returned to the pool.

**Comment by josephschorr** [comment] 2023-05-11 20:34
Closing as per @jason-who-codes's attempt to reproduce; will re-open if an issue is reported

**Closed by josephschorr** 2023-05-11 20:34 UTC
Labels: area/datastore
