### ISSUE TITLE
Periodic timeouts with the Spanner datastore

### ISSUE THREAD

**Issue by byuTamao** [authzed/spicedb#1196] opened 2023-03-09 08:25 UTC
Please advise if there's an issue format requirement for your repo!

**Environment**:
- Google Cloud GKE cluster
- Google spanner as database (capacity is 5000 for production, and 1000 for dev)
- Use kubernetes operator to deploy spicedb
- Currently we have two spicedb instances with different namespaces
- Node machine type is `n2d-standard-8`

**What happened?**
We have three incidents since we get the spicedb running. All the requests sent to spicedb (including basic read schema command) are timeout when the incident happens

**What measurements have we taken?**
- upgrade spicedb version to v1.16.1 from v1.11
- set up extra alerts to monitor the GCLB timeout
- set up spanner session number metrics monitoring since timeout issue always happens when session number comes to a peak
- increase spanner capacity (obviously not working)

**How do we solve the alerts?**
Just rollout restarting the spicedb pods works. The spanner session number drops along with the restarts

**What have we found so far?**
- The incidents usually happen when spanner session number comes to a peak (~1300 in our case)
<img width="808" alt="image" src="https://user-images.githubusercontent.com/103073199/223962132-580b50f1-c5ff-4342-8caf-38522a885b17.png">
<img width="794" alt="image" src="https://user-images.githubusercontent.com/103073199/223962184-14d761e1-056e-4b9b-965b-5855c1c7e8e1.png">

- According to the logs of spicedb, there's issue with the spanner connection
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/103073199/223962514-962c1ae9-a2a4-467f-87a5-9dd4b4a371a8.png">

- Two spicedb pods (since we have 2 tenants) tend to have timeout issues around the same time. And restarts always solves the issue (though temporarily)
- I enabled SessionPoolConfig.TrackSessionHandles in dev. Since it's hardcoded when a spanner client is created, I have to change the code and rebuild it locally, and deploy it. In this way we might find more detailed logs (as the error log suggested), but we have to wait for the next incident happens

According to the spanner session number diagram, it might because of session leak. However the session number is not too high comparing to our capacity, and we don't have much traffic. I'm also wondering if anyone uses Google spanner has a similar issue. Thanks in advance!

**Comment by jzelinskie** [comment] 2023-03-10 22:00
This seems related: https://github.com/googleapis/google-cloud-go/issues/7527

**Comment by jzelinskie** [comment] 2023-03-10 22:15
Since you've been building SpiceDB yourself, can you confirm the version of the Spanner client library being used?
Also has running with the session tracking yielded any new information?

**Comment by byuTamao** [comment] 2023-03-10 22:31
We're using spanner client v1.42.0

Usually it takes around 14 days for us to see the problem again, so it's hard to reproduce it.

We built based on v1.16.1 previously (with the session tracking enabled), however the pods were accidentally restarted today morning :(. Now I just rebuilt it based on v1.17.0 and deployed, and lower the spanner capacity to 100 to see if can help reproduce the problem faster in dev

**Comment by Grubana** [comment] 2023-03-13 07:18
Hello,

We have exactly the same problem. 

Our setup is pretty much the same:
- GKE Cluster
- SpiceDB 1.16.1 (official container)
- Spanner (dedicated for SpiceDB, 700 capacity for production, 300 for staging environment)

In my case i can't confirm that it has something to do with the number of sessions. 
In the last weeks it happened three times, the interval for the error to occur is around 7 days.

The last occurrence of the error was today at 06:21. For me, there is no peak in the session count at that time.
![image](https://user-images.githubusercontent.com/1355287/224630658-fcb6bc9b-279f-419e-af4e-69bfe2ec1fba.png)

Every time the issue occurred, both environments failed simultaneously.
The setup of the environments is completely separated (own gcloud project for each stage).

Restarting all pods solves the problem, as mentioned before.

**Comment by jzelinskie** [comment] 2023-03-13 15:10
Thanks for the additional information @Grubana.

Did you perform any changes before your first observation? For example, did you upgrade SpiceDB?

**Comment by ecordell** [comment] 2023-03-15 14:29
@Grubana @byuTamao Can we try to rule out issues with workload identity?

What versions of kubernetes are you using?

Do you see any failing pods in `kube-system`, or any unusual logs in `gke-metadata-server` pods?

**Comment by byuTamao** [comment] 2023-03-20 17:41
Hi @ecordell sorry for the late reply!

We enabled cluster auto-upgrade, and the latest issue we caught was on 1.24.9-gke.3200. There's no log in `gke-metadata-server`, and no error log in `kube-system` when the issue happened

**Comment by byuTamao** [comment] 2023-03-20 17:59
We just managed to catch the issue in dev, with `SessionPoolConfig.TrackSessionHandles` enabled. It printed out a lot of logs. I'll paste first a few lines here (only for session 1, as you can find in the logs), and hope it helps:
```
{"level":"error","requestID":"f75583aa01ce012bdde3238d706c5c28","error":"unable to load revision: spanner: code = \"Canceled\", desc = \"timeout / context canceled during getting session.\", additional information = \n\nSession 1 checked out of pool at 2023-03-10T22:54:21Z by goroutine:\ngoroutine 1 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ncloud.google.com/go/spanner.(*sessionPool).newSessionHandle(0xc000770000, 0xc0007ef3f0)\n\t/go/src/app/vendor/cloud.google.com/go/spanner/session.go:796 +0x238\ncloud.google.com/go/spanner.(*sessionPool).take(0xc000770000, {0x252afb8, 0xc000e93680})\n\t/go/src/app/vendor/cloud.google.com/go/spanner/session.go:942 +0x9c5\ncloud.google.com/go/spanner.(*ReadOnlyTransaction).acquireSingleUse(0xc000e3f040, {0x252afb8, 0xc000e93680})\n\t/go/src/app/vendor/cloud.google.com/go/spanner/transaction.go:691 +0x359\ncloud.google.com/go/spanner.(*ReadOnlyTransaction).acquire(0xc000e3f040, {0x252afb8, 0xc000e93680})\n\t/go/src/app/vendor/cloud.google.com/go/spanner/transaction.go:668 +0x54\ncloud.google.com/go/spanner.(*txReadOnly).ReadWithOptions(0xc000e3f048, {0x252af48?, 0xc000128000?}, {0x2078de2, 0x8}, {0x250f6e0, 0x37b84d0}, {0xc000ebc080, 0x1, 0x1}, ...)\n\t/go/src/app/vendor/cloud.google.com/go/spanner/transaction.go:193 +0x1cf\ncloud.google.com/go/spanner.(*txReadOnly).Read(...)\n\t/go/src/app/vendor/cloud.google.com/go/spanner/transaction.go:129\ngithub.com/authzed/spicedb/internal/datastore/spanner.spannerDatastore.Statistics({0xc000615800, {}, 0xc0002ee4d0, {0x400, 0x12a05f200, 0x11e1a3000, 0x3fb999999999999a, 0x4e94914f0000, 0x31248bd48c, 0x1, ...}, ...}, ...)\n\t/go/src/app/internal/datastore/spanner/stats.go:18 +0xf0\ngithub.com/authzed/spicedb/internal/datastore/proxy.(*observableProxy).Statistics(0xc000777de0, {0x252af80?, 0xc000eb0240?})\n\t/go/src/app/internal/datastore/proxy/observable.go:123 +0xb5\ngithub.com/authzed/spicedb/internal/telemetry.RegisterTelemetryCollector({0xc0005cb1c0, 0x7}, {0x2537270?, 0xc000777de0})\n\t/go/src/app/internal/telemetry/metrics.go:35 +0x235\ngithub.com/authzed/spicedb/pkg/cmd/server.(*Config).Complete(0xc000436000, {0x252af48, 0xc000128000})\n\t/go/src/app/pkg/cmd/server/server.go:352 +0x2715\ngithub.com/authzed/spicedb/pkg/cmd.NewServeCommand.func1(0xc0000fb500?, {0x37b84d0?, 0x0?, 0x0?})\n\t/go/src/app/pkg/cmd/serve.go:138 +0x37\ngithub.com/spf13/cobra.(*Command).execute(0xc0000fb500, {0x37b84d0, 0x0, 0x0})\n\t/go/src/app/vendor/github.com/spf13/cobra/command.go:916 +0x862\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc0000fa000)\n\t/go/src/app/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/go/src/app/vendor/github.com/spf13/cobra/command.go:968\nmain.main()\n\t/go/src/app/cmd/spicedb/main.go:95 +0x6bc\n\n\n
```

The rest of the logs are for `session 2/3/...` and they look like the same

**Comment by ecordell** [comment] 2023-03-20 19:24
@byuTamao That was very helpful! Ruling out those issues led me to this: https://github.com/authzed/spicedb/pull/1212 which I think will fix the issue

**Comment by ecordell** [comment] 2023-03-20 19:48
Re-opening just until we confirm this was the fix

**Comment by byuTamao** [comment] 2023-03-20 19:51
Thank you @ecordell! please keep us posted when you move the change to a release!

**Comment by Grubana** [comment] 2023-03-21 06:28
Thank you, looking forward for a release and keeping you updated

**Comment by ecordell** [comment] 2023-03-30 17:23
@byuTamao confirmed that they don't see the issue anymore, closing 🎉

**Closed by ecordell** 2023-03-30 17:23 UTC
Labels: kind/bug, priority/1 high, area/perf, area/datastore
