### ISSUE TITLE
Flake: TestPostgresDatastore/postgres-16-head-/GarbageCollection

### ISSUE THREAD

**Issue by vroldanbet** [authzed/spicedb#1614] opened 2023-10-26 09:15 UTC
See https://github.com/authzed/spicedb/actions/runs/6651666420/job/18074976820?pr=1613
```
--- FAIL: TestPostgresDatastore (0.00s)
    --- FAIL: TestPostgresDatastore/postgres-16-head- (80.94s)
        --- FAIL: TestPostgresDatastore/postgres-16-head-/GarbageCollection (0.19s)
            postgres_test.go:362: 
                	Error Trace:	/home/runner/actions-runner/_work/spicedb/spicedb/internal/datastore/postgres/postgres_test.go:362
                	            				/home/runner/actions-runner/_work/spicedb/spicedb/internal/datastore/postgres/postgres_test.go:231
                	Error:      	Not equal: 
                	            	expected: 2
                	            	actual  : 1
                	Test:       	TestPostgresDatastore/postgres-[16](https://github.com/authzed/spicedb/actions/runs/6651666420/job/18074976820?pr=1613#step:4:17)-head-/GarbageCollection
FAIL
FAIL	github.com/authzed/spicedb/internal/datastore/postgres	90.486s
```

**Comment by josephschorr** [comment] 2023-10-27 18:08
Duplicate of #1559

**Closed by josephschorr** 2023-10-27 18:08 UTC
Labels: kind/flake
