### ISSUE TITLE
Unable to cleanly shut down SpiceDB process with REST gateway running

### ISSUE THREAD

**Issue by Meai** [authzed/spicedb#1126] opened 2023-01-30 15:01 UTC
On a nearly completely empty mysql+spicedb where I only added the sample schema with nothing else, I'm getting a ton of errors (like 50 per second) and it wont turn off properly anymore until I kill the process:

 ```
3:55PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=-0.000001
```

trying to shut down:

```
4:02PM INF shutting down datastore garbage collection worker
4:02PM ERR error waiting for garbage collector to shutdown error="context canceled"
4:02PM ERR error waiting for garbage collector to shutdown error="context canceled"
```

the shutdown problem even happens when i try to shut down immediately, before the scan errors happen.
I'm now trying adding ?parseTime=true to the connection string but I can already say that shutting down via ctrl+c still doesn't work, even after adding that. I saw that advice [here on stackoverflow](https://stackoverflow.com/questions/45040319/unsupported-scan-storing-driver-value-type-uint8-into-type-time-time)

**Comment by josephschorr** [comment] 2023-01-30 17:58
@Meai What version of MySQL are you running against? Can you add `--log-level=trace` and retrieve the logs for the failure?

**Comment by Meai** [comment] 2023-01-30 18:52
> @Meai What version of MySQL are you running against? Can you add `--log-level=trace` and retrieve the logs for the failure?

mysqld 8.0.31

for the shutdown via ctrl+c I dont see any new logs, it just always hangs forever. 
here are the logs with tracing enabled and no ?parseTime=true in the connectionstring:


```
7:47PM INF finished call grpc.code=OK grpc.component=server grpc.method=CheckPermission grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-01-30T19:47:38+01:00 grpc.time_ms=0.214 peer.address=127.0.0.1:58040 protocol=grpc requestID=a60128bb01a5878eac8e3bbdbd3c6fa4
7:47PM DBG returning cached revision now=2023-01-30T19:47:39+01:00 requestID=a3182e1c23369dfbb79914a3d46f3680 valid=2023-01-30T19:47:40+01:00
7:47PM TRC adding sample duration to statistics duration=0.050666 requestID=a3182e1c23369dfbb79914a3d46f3680
7:47PM INF finished call grpc.code=OK grpc.component=server grpc.method=CheckPermission grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-01-30T19:47:39+01:00 grpc.time_ms=0.203 peer.address=127.0.0.1:58040 protocol=grpc requestID=a3182e1c23369dfbb79914a3d46f3680
7:47PM DBG computing new revision now=2023-01-30T19:47:40+01:00 requestID=2f238c969f9b989a56c4f8956e1a7f21 valid=2023-01-30T19:47:40+01:00
7:47PM DBG setting valid through now=2023-01-30T19:47:40+01:00 requestID=2f238c969f9b989a56c4f8956e1a7f21 valid=2023-01-30T19:47:45+01:00 validFor=4.225654s
7:47PM TRC adding sample duration to statistics duration=0.368239 requestID=2f238c969f9b989a56c4f8956e1a7f21
7:47PM INF finished call grpc.code=OK grpc.component=server grpc.method=CheckPermission grpc.method_type=unary grpc.service=authzed.api.v1.PermissionsService grpc.start_time=2023-01-30T19:47:40+01:00 grpc.time_ms=0.517 peer.address=127.0.0.1:58040 protocol=grpc requestID=2f238c969f9b989a56c4f8956e1a7f21
7:47PM DBG reported telemetry endpoint=https://telemetry.authzed.com next=1h0m0s
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.091668 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=533.035477
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.097885 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=391.840729
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.070183 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=1301.186937
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.065994 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=2122.007588
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.06549 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=1846.861189
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.073159 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=5390.682109
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.065294 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=6013.783084
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.122952 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=6199.383043
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.088397 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=16005.543728
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.060033 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=16162.681384
7:50PM DBG datastore garbage collection completed collected={"namespaces":0,"relationships":0,"transactions":0} duration=0.104858 highestTxID=null
7:50PM WRN error attempting to perform garbage collection error="sql: Scan error on column index 0, name \"UTC_TIMESTAMP(6)\": unsupported Scan, storing driver.Value type []uint8 into type *time.Time" next-attempt-in=25933.421626
```

**Comment by josephschorr** [comment] 2023-01-30 19:47
@Meai and with `parseTime=true`, you do not see the errors but it still can't shutdown?

**Comment by Meai** [comment] 2023-01-31 02:53
> @Meai and with `parseTime=true`, you do not see the errors but it still can't shutdown?

yes!

**Comment by josephschorr** [comment] 2023-01-31 17:20
@Meai I'm unable to reproduce; when I shutdown the process, I see the context-canceled "errors", but those are normal and then the process immediately shuts down.

Are you saying you see the errors but then the shutdown hangs, or..?

**Comment by mihaivint** [comment] 2023-02-02 12:35
I seem to experience simillar issues, but the issue seems related to http server, was closing fine before i've enabled it :
`Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","format":"auto","log_level":"info","provider":"zerolog","async":false,"time":"2023-02-02T14:32:25+02:00","message":"configured logging"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","v":0,"provider":"none","endpoint":"","service":"spicedb","insecure":false,"sampleRatio":0.2,"time":"2023-02-02T14:32:25+02:00","message":"configured opentelemetry traci>
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","time":"2023-02-02T14:32:25+02:00","message":"using mysql datastore engine"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","timeout":1,"time":"2023-02-02T14:32:25+02:00","message":"overriding innodb_lock_wait_timeout"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","initialSlowRequest":"10ms","maxRequests":1000000,"hedgingQuantile":0.95,"time":"2023-02-02T14:32:25+02:00","message":"request hedging enabled"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","maxCost":"16 MiB","numCounters":1000,"metrics":false,"time":"2023-02-02T14:32:25+02:00","message":"configured namespace cache"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","maxCost":"1.2 GiB","numCounters":10000,"metrics":false,"time":"2023-02-02T14:32:25+02:00","message":"configured dispatch cache"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","check-permission":50,"lookup-resources":50,"lookup-subjects":50,"reachable-resources":50,"time":"2023-02-02T14:32:25+02:00","message":"configured dispatch concurrency l>
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","maxCost":"2.7 GiB","numCounters":100000,"metrics":false,"time":"2023-02-02T14:32:25+02:00","message":"configured cluster dispatch cache"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":50053","network":"tcp","service":"dispatch-cluster","workers":0,"insecure":true,"time":"2023-02-02T14:32:25+02:00","message":"grpc server started serving"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":50051","network":"tcp","service":"grpc","workers":0,"insecure":true,"time":"2023-02-02T14:32:25+02:00","message":"grpc server started serving"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","upstream":":50051","time":"2023-02-02T14:32:25+02:00","message":"starting REST gateway"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","interval":180000,"time":"2023-02-02T14:32:25+02:00","message":"datastore garbage collection worker started"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":9090","service":"metrics","insecure":true,"time":"2023-02-02T14:32:25+02:00","message":"http server started serving"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":8080","service":"dashboard","insecure":true,"time":"2023-02-02T14:32:25+02:00","message":"http server started serving"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","time":"2023-02-02T14:32:25+02:00","message":"telemetry disabled"}
Feb 02 14:32:25 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":8443","service":"http","insecure":true,"time":"2023-02-02T14:32:25+02:00","message":"http server started serving"}
Feb 02 14:33:35 spice-2.novalocal systemd[1]: Stopping SpiceDB...
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","time":"2023-02-02T14:33:35+02:00","message":"received interrupt"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","time":"2023-02-02T14:33:35+02:00","message":"shutting down"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":9090","service":"metrics","time":"2023-02-02T14:33:35+02:00","message":"http server stopped serving"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":8080","service":"dashboard","time":"2023-02-02T14:33:35+02:00","message":"http server stopped serving"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":50051","network":"tcp","service":"grpc","time":"2023-02-02T14:33:35+02:00","message":"grpc server stopped serving"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","addr":":50053","network":"tcp","service":"dispatch-cluster","time":"2023-02-02T14:33:35+02:00","message":"grpc server stopped serving"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"info","time":"2023-02-02T14:33:35+02:00","message":"shutting down datastore garbage collection worker"}
Feb 02 14:33:35 spice-2.novalocal spicedb[522393]: {"level":"error","error":"context canceled","time":"2023-02-02T14:33:35+02:00","message":"error waiting for garbage collector to shutdown"}
[root@spice-2 ~]# ss -tlpn
State                    Recv-Q                   Send-Q                                      Local Address:Port                                       Peer Address:Port                   Process
LISTEN                   0                        128                                               0.0.0.0:22                                              0.0.0.0:*                       users:(("sshd",pid=1194,fd=5))
LISTEN                   0                        128                                                  [::]:22                                                 [::]:*                       users:(("sshd",pid=1194,fd=7))
LISTEN                   0                        128                                                     *:8443                                                  *:*                       users:(("spicedb",pid=522393,fd=21))
`

**Comment by Meai** [comment] 2023-02-02 17:13
> --http-enabled=true

I think you are right, that parameter makes all the difference. With it I cant shut down anymore

**Closed** 2023-02-02 20:18 UTC
Labels: kind/bug, priority/2 medium, area/datastore
