### ISSUE TITLE
Language Server

### ISSUE THREAD

**Issue by lukewestby** [authzed/spicedb#412] opened 2022-02-09 22:18 UTC
Hi folks!

This issue is a request for a language server implementation to support schema editing in code editors. I'm filing this as requested by I believe @josephschorr [in the discord](https://discord.com/channels/844600078504951838/844600078948630559/941093583438622762).

**Comment by jzelinskie** [comment] 2022-02-09 22:52
Duplicate of #179

**Closed by jzelinskie** 2022-02-09 22:52 UTC
Labels: priority/3 low, area/tooling, state/gauging interest, area/api devtools
