### ISSUE TITLE
Bug on "fullyConsistent": true for relationwrite (OPERATION_CREATE+OPERATION_DELETE) when using Postgres data store

### ISSUE THREAD

**Issue by muntdan** [authzed/spicedb#1215] opened 2023-03-21 07:36 UTC
Business case:
I have a structure that includes teams with 3 level of users: read-only/ write-read/ admin(delete right).
I built an UI for the user management and in there the level of the users can be altered (from read-only to admin or any other combination) which results in a relationships/write call with 2 items inside: OPERATION_CREATE with the new relation and OPERATION_DELETE for the old one.
Without storing the zedtoken after a change, refreshing the UI with Consistency level "fullyConsistent": true some times will not return the new state for 5-6 seconds but it can take up to 60 seconds in some rare cases.

**Comment by Perseus** [comment] 2023-03-21 09:28
I think the `fully_consistent` consistency level would work for this

**Comment by muntdan** [comment] 2023-03-21 09:43
You would think, but no. 
I just re-tested right now and it still takes a 1-5 seconds for it to permissions/subjects even with "fullyConsistent": true to start bringing the correct user list.

**Comment by vroldanbet** [comment] 2023-03-21 09:49
@muntdan fully consistent should do what you want. What datastore are you using? We recently detected a problem in PostgreSQL datastore and you may be hitting it: https://github.com/authzed/spicedb/pull/1153

**Comment by muntdan** [comment] 2023-03-21 09:49
Indeed I am using Postgres 15 as data store.

**Comment by vroldanbet** [comment] 2023-03-21 09:51
@muntdan can you build SpiceDB from `main`? It includes the fix. Otherwise we are planning to release 1.18.0 in the coming days

**Comment by muntdan** [comment] 2023-03-21 09:54
I updated task description, and will await for version 1.18 
as I am not a go developer and only use the already built docker version and connect to its grpc api from c#.

**Comment by vroldanbet** [comment] 2023-03-21 09:55
Closing as this should be fixed in `main` via https://github.com/authzed/spicedb/pull/1153, please reopen if the problem persists in 1.18.0

Duplicate of https://github.com/authzed/spicedb/issues/1130

**Comment by vroldanbet** [comment] 2023-03-21 09:56
Closing as this should be fixed in `main` via https://github.com/authzed/spicedb/pull/1153, please reopen if the problem persists in 1.18.0

Duplicate of https://github.com/authzed/spicedb/issues/1130

**Closed by vroldanbet** 2023-03-21 09:56 UTC
